const _ResponseTypes = {
    EDIX12: "application/EDI-X12",
    EDITFACT: "application/EDIFACT",
    app_javascript: "application/javascript",
    app_octetStream: "application/octet-stream",
    app_ogg: "application/ogg",
    app_pdf: "application/pdf",
    app_xhtml_xml:"application/xhtml+xml",
    app_xShockwaveFlash: "application/x-shockwave-flash ",
    app_json: "application/json",
    app_ld_json:"application/ld+json",
    app_xml: "application/xml",
    app_zip: "application/zip",
    app_xwww_formUrlEncoded: "application/x-www-form-urlencoded ",
    audio_mpeg: "audio/mpeg",
    audio_xMsWma: "audio/x-ms-wma",
    audio_vnd_realAudio: "audio/vnd.rn-realaudio",
    audio_xWav:"audio/x-wav",
    multipart_mixed:"multipart/mixed",
    multipart_alternative:"multipart/alternative",
    multipart_related: "multipart/related",
    multipart_formData: "multipart/form-data",
    text_css: "text/css",
    text_csv: "text/csv ",
    text_html: "text/html ",
    text_javascript: "text/javascript (obsolete)",
    text_plain: "text/plain",
    text_xml: "text/xml",
    video_mpeg: "video/mpeg ",
    video_mp4: "video/mp4 ",
    video_quicktime: "video/quicktime ",
    video_x_ms_wMV: "video/x-ms-wmv ",
    video_msVideo: "video/x-msvideo ",
    video_xFlv: "video/x-flv",
    video_webM: "video/webm",
    app_vnd_oasisOpenDocumentText: "application/vnd.oasis.opendocument.text ",
    app_vnd_oasisOpenDocumentSpreadsheet: "application/vnd.oasis.opendocument.spreadsheet",
    app_vnd_oasisOpenDocumentPresentation: "application/vnd.oasis.opendocument.presentation",
    app_vnd_oasisOpenDocumentGraphics: "application/vnd.oasis.opendocument.graphics",
    app_vnd_msExcel: "application/vnd.ms-excel ",
    app_vnd_openXmlFormats_officeDocument_spreadsheet: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    app_vnd_msPowerpoint: "application/vnd.ms-powerpoint ",
    app_vnd_openXmlFormats_officeDocument_presentation: "application/vnd.openxmlformats-officedocument.presentationml.presentation ",
    app_vnd_msWord: "application/msword",
    app_vnd_openXmlFormats_officeDocument_document: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    app_vnd_mozilla_xul_xml: "application/vnd.mozilla.xul+xml",
};

console.log('IMPORTEDDD');
export const ResponseTypes = _ResponseTypes;